version: '3'
services:
  php: 
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./php-code:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootWord
      MYSQL_ROOT_USERNAME: root
      MYSQL_DATABASE: visitors